# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]

  - repo: https://github.com/frostming/fix-future-annotations
    rev: 0.5.0
    hooks:
      - id: fix-future-annotations

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        additional_dependencies:
          - boto3-stubs[essential,lambda]==1.40.41
          - decouple-types==1.0.2
          - types-PyYAML==6.0.12.20250915
          - types-beautifulsoup4==4.12.0.20250516
          - types-html5lib==1.1.11.20250917
          - types-openpyxl==3.1.5.20250919
          - types-python-dateutil==2.9.0.20250822
          - types-toml==0.10.8.20240310
          - types-xmltodict==1.0.1.20250920
        exclude: "tests"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "tests/dicts/io/input/"
      - id: check-yaml
      - id: check-added-large-files
        exclude: "images/"
