os: linux
language: python
cache: pip
jobs:
  include:
    - python: "2.7"
      env:
        - TOX_ENV=py27
    - python: "3.5"
      env:
        - TOX_ENV=py35
    - python: "3.6"
      env:
        - TOX_ENV=py36
    - dist: xenial
      language: python
      python: "3.7"
      env:
        - TOX_ENV=py37
    - dist: xenial
      language: python
      python: "3.8"
      env:
        - TOX_ENV=py38
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
